spring:
  profiles:
    active: dev
    group:
      dev:
        - dev
      prod:
        - prod

# 개발용
---
# MYSQL 설정
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
    generate-ddl: true

  thymeleaf:
    cache: false

  kafka:
    consumer:
      enable-auto-commit: true
      max-poll-records: 1000
  
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          socketFactory.class: javax.net.ssl.SSLSocketFactory
          auth: true
          starttls:
            eanble: true

jwt:
  secret: mythologyteamtest

# 배포용
---
spring:
  config:
    activate:
      on-profile: prod

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate